[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-requirements-txt", "hatchling",]

[project]
classifiers = [ "Programming Language :: Python", "Programming Language :: Python :: 3",]
description = "upload python package via twine"
dynamic = [ "dependencies", "version",]
keywords = [ "twine", "wheel",]
license-files = [ "LICENSE",]
name = "xpip-upload"
requires-python = ">=3.8"
[[project.authors]]
name = "Mingzhe Zou"
email = "zoumingzhe@outlook.com"

[project.readme]
content-type = "text/markdown"
file = "readme.md"

[project.scripts]
xpip-upload = "xpip_upload.cmds:main"

[project.urls]
Homepage = "https://github.com/bondbox/xpip/"

[tool.hatch.version]
path = "xpip_upload/attribute.py"

[tool.hatch.build.targets.sdist]
exclude = [ "xpip_upload/unittest",]
packages = [ "xpip_upload",]

[tool.hatch.build.targets.wheel]
exclude = [ "xpip_upload/unittest",]
packages = [ "xpip_upload",]

[tool.hatch.metadata.hooks.requirements_txt]
files = [ "requirements.txt",]

[tool.hatch.build.targets.sdist.force-include]

[tool.hatch.build.targets.wheel.force-include]
