[pypi]
url = "https://pypi.org/simple"

[tsinghua]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[ustc]
url = "https://pypi.mirrors.ustc.edu.cn/simple"

[baidu]
url = "https://mirror.baidu.com/pypi/simple"

[aliyun]
url = "https://mirrors.aliyun.com/pypi/simple"

[douban]
url = "https://pypi.douban.com/simple"
