[build-system]
build-backend = "hatchling.build"
requires = [
    "hatch-requirements-txt",
    "hatchling",
]

[project]
authors = [
    { name = "Mingzhe Zou", email = "zoumingzhe@outlook.com" },
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
description = "Python package. Build. Install."
dynamic = [
    "dependencies",
    "version",
]
keywords = [
    "build",
    "setuptools",
    "wheel",
]
name = "xpip-build"
requires-python = ">=3.8"

[project.license]
file = "LICENSE"

[project.readme]
content-type = "text/markdown"
file = "readme.md"

[project.scripts]
xpip-build = "xpip_build.cmds:main"

[project.urls]
Homepage = "https://github.com/bondbox/xpip/"

[tool.hatch.build.targets.sdist]
exclude = [
    "xpip_build/unittest",
]
packages = [
    "xpip_build",
]

[tool.hatch.build.targets.wheel]
exclude = [
    "xpip_build/unittest",
]
packages = [
    "xpip_build",
]

[tool.hatch.metadata.hooks.requirements_txt]
files = [
    "requirements.txt",
]

[tool.hatch.version]
path = "xpip_build/attribute.py"
