[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-requirements-txt", "hatchling",]

[project]
classifiers = [ "Programming Language :: Python", "Programming Language :: Python :: 3",]
description = "Python package. Build. Install."
dynamic = [ "dependencies", "version",]
keywords = [ "build", "setuptools", "wheel",]
license-files = [ "LICENSE",]
name = "xpip-build"
requires-python = ">=3.8"
[[project.authors]]
name = "Mingzhe Zou"
email = "zoumingzhe@outlook.com"

[project.readme]
content-type = "text/markdown"
file = "readme.md"

[project.scripts]
xpip-build = "xpip_build.cmds:main"

[project.urls]
Homepage = "https://github.com/bondbox/xpip/"

[tool.hatch.version]
path = "xpip_build/attribute.py"

[tool.hatch.build.targets.sdist]
exclude = [ "xpip_build/unittest",]
packages = [ "xpip_build",]

[tool.hatch.build.targets.wheel]
exclude = [ "xpip_build/unittest",]
packages = [ "xpip_build",]

[tool.hatch.metadata.hooks.requirements_txt]
files = [ "requirements.txt",]

[tool.hatch.build.targets.sdist.force-include]

[tool.hatch.build.targets.wheel.force-include]
